# NumPy Assignment

Complete the exercises below to test your understanding of NumPy. Each question tells you what output or result is expected. Write your code in the provided code cells.

**Topics covered:**
- Creating arrays (from lists, built-in methods)
- Random number generation
- Array attributes and methods
- Indexing and slicing
- Broadcasting
- Boolean masking
- NumPy operations

In [ ]:
# Run this cell first!
import numpy as np

---
## Part 1: Creating Arrays

### Q1. Convert the following Python list into a NumPy array and store it in a variable called `arr1`.
```python
my_list = [10, 20, 30, 40, 50]
```

In [ ]:
# Your code here
import numpy as np
my_list = [10, 20, 30, 40, 50]
np.array(my_list)

array([10, 20, 30, 40, 50])

*italicized text:*### Q2. Convert the following list of lists into a 2D NumPy array and store it in `mat1`.
```python
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]



```

In [ ]:
# Your code here
import numpy as np
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
mat1=np.array(my_matrix)
print(mat1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Q3. Use `np.arange` to create an array of all even numbers from 0 to 20 (inclusive).

In [ ]:
# Expected output: array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])
# Your code here
import numpy as np
arr=np.arange(0,21,2)
print(arr)

[ 0  2  4  6  8 10 12 14 16 18 20]


### Q4. Create a 4x4 array of all zeros.

In [ ]:
# Your code here
import numpy as np
arr=np.zeros((4,4),dtype=int)
print(arr)
print()
# onther way
arr2=np.full((4,4),0)
print(arr2)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


### Q5. Create a 3x5 array of all ones.

In [ ]:
# Your code here
import numpy as np
arr=np.ones((3,5))
print(arr)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


### Q6. Use `np.linspace` to create an array of 10 evenly spaced values between 0 and 5.

In [ ]:
# Your code here
import numpy as np
arr=np.linspace(0,5,10)
print(arr)


[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


### Q7. Create a 5x5 identity matrix using NumPy.

In [ ]:
# Your code here
import numpy as np
arr=np.eye(5,5)
print(arr)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


---
## Part 2: Random Number Generation

### Q8. Create a 3x3 array of random floats drawn from a uniform distribution between 0 and 1.

In [ ]:
# Your code here
import numpy as np
arr=np.random.rand(3,3 )
print(arr)

[[0.0891684  0.24442775 0.37050647]
 [0.81028489 0.51662308 0.5243199 ]
 [0.47312821 0.61859207 0.56596076]]


### Q9. Create a 1D array of 5 random floats drawn from a standard normal distribution.

In [ ]:
# Your code here
import numpy as np
rng=np.random.default_rng()
randomnumber=rng.uniform(0,1,5)
print(randomnumber)


[0.50483452 0.50862836 0.24875514 0.79113426 0.19115727]


### Q10. Create an array of 8 random integers between 1 and 100 (inclusive of 1, exclusive of 100).

In [ ]:
# Your code here
import numpy as np
np.random.seed(42)
arr=np.random.randint(1,100,8)
print(arr)

#other way
#rng=np.random.default_rng()
#arr=rng.integers(1,100,8)
#print(arr)





[52 93 15 72 61 21 83 87]


---
## Part 3: Array Attributes & Methods

Run the cell below to create the arrays you'll use for this section.

In [ ]:
import numpy as np
np.random.seed(42)
arr=np.random.randint(1,100,8)
#Array Attributes
print(arr)
print(" dim",arr.ndim)
print("size ",arr.size)
print("number bytes",arr.nbytes)
print("index max number",arr.argmax)
print("index min number",arr.argmin)
print("type arr",arr.dtype)
print("shape ",arr.shape)
print()
#Methods in array
print()
print("sum of element",arr.sum())
print("المتوسط الحسابي",arr.mean())
print("min number ",arr.min())
print("max number",arr.max())
print("الانحراف المعياري",arr.std())
print("التباين ",arr.var())


[52 93 15 72 61 21 83 87]
 dim 1
size  8
number bytes 64
index max number <built-in method argmax of numpy.ndarray object at 0x7ea0d24bf8d0>
index min number <built-in method argmin of numpy.ndarray object at 0x7ea0d24bf8d0>
type arr int64
shape  (8,)


sum of element 484
المتوسط الحسابي 60.5
min number  15
max number 93
الانحراف المعياري 27.613402542968153
التباين  762.5


### Q11. Reshape `arr` into a 6x6 matrix.

In [ ]:
# Your code here
import numpy as np
np.random.seed(42)
arr=np.random.randint(1,100,8)
print(arr)
print()
ranarr=np.arange(36)
ranarr=arr.reshape(6,6)
print(ranarr)


[52 93 15 72 61 21 83 87]

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


### Q12. Find the maximum value in `ranarr`.

In [ ]:
# Your code here
import numpy as np
print(ranarr.max())

35


### Q13. Find the index position of the minimum value in `ranarr`.

In [ ]:
# Your code here
print("index of min number in array ",ranarr.argmin())

index of min number in array  0


### Q14. What is the shape of `arr`? What is its shape after reshaping to (1, 36)?

In [ ]:
# Your code here
print(arr.shape)
print(ranarr.shape)


(36,)
(6, 6)


### Q15. What is the data type (`dtype`) of the elements in `arr`?

In [ ]:
# Your code here
print(arr.dtype)

int64


---
## Part 4: Indexing and Slicing

Run the cell below to set up the array for this section.

In [ ]:
arr = np.arange(0, 11)
mat = np.arange(1, 26).reshape(5, 5)
print('arr:', arr)
print('mat:\n', mat)

arr: [ 0  1  2  3  4  5  6  7  8  9 10]
mat:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


### Q16. From `arr`, retrieve the value at index 7.

In [ ]:
# Expected output: 7
# Your code here
print(arr[7])

7


### Q17. From `arr`, retrieve values from index 3 to 7 (inclusive of 3, exclusive of 7).

In [ ]:
# Expected output: array([3, 4, 5, 6])
# Your code here
print(arr[3:7])


[3 4 5 6]


### Q18. From `mat`, retrieve the bottom-right 3x3 submatrix.
Expected output:
```
array([[13, 14, 15],
       [18, 19, 20],
       [23, 24, 25]])
```

In [ ]:
# Your code here
print(mat[2:,2:5])


[[13 14 15]
 [18 19 20]
 [23 24 25]]


### Q19. From `mat`, retrieve only the element `17`.

In [ ]:
# Expected output: 17
# Your code here
import numpy as np
mat = np.arange(1, 26).reshape(5, 5)
print('mat:\n', mat)
print(mat[3:4,1:2])


mat:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[17]]


### Q20. From `mat`, retrieve the first column as a 2D column vector (shape should be (5,1)).
Expected output:
```
array([[ 1],
       [ 6],
       [11],
       [16],
       [21]])
```

In [ ]:
# Your code her
print(mat[:,:1:4])

[[ 1]
 [ 6]
 [11]
 [16]
 [21]]


### Q21. From `mat`, retrieve the entire third row.
Expected output: `array([11, 12, 13, 14, 15])`

In [ ]:
# Your code here
print(mat[2])

[11 12 13 14 15]


---
## Part 5: Broadcasting

### Q22. Using `arr = np.arange(0, 11)`, set all values from index 2 to 5 (inclusive) to the value `50`. Print the result.

In [ ]:
arr = np.arange(0, 11)
# Your code here
arr[2:6]=50
print(arr)

[ 0  1 50 50 50 50  6  7  8  9 10]


### Q23. Create a copy of `arr` (from its original state below) and set all values to 0 in the copy. Verify that the original `arr` is unchanged.

In [ ]:
arr = np.arange(0, 11)
# Your code here — create a copy, modify the copy, then print both
arrc=arr.copy()
arrc[:]=0
print(arrc)
print(arr)

[0 0 0 0 0 0 0 0 0 0 0]
[ 0  1  2  3  4  5  6  7  8  9 10]


---
## Part 6: Boolean Masking & Conditional Selection

Run the cell below first.

In [ ]:
arr = np.arange(1, 21)  # 1 through 20
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

### Q24. Create a boolean mask for all values in `arr` that are greater than 10, and use it to retrieve those values.

In [ ]:
# Expected output: array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
# Your code here
arr1=[arr>10]
print(arr1)

[array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])]


### Q25. Retrieve all even numbers from `arr` using boolean indexing.
*Hint: use the modulo operator `%`*

In [ ]:
# Expected output: array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])
# Your code here
print(arr[arr %2==0])



[ 2  4  6  8 10 12 14 16 18 20]


---
## Part 7: NumPy Operations & Statistics

Run this cell to set up `mat`.

In [ ]:
mat = np.arange(1, 26).reshape(5, 5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Q26. Get the sum of all values in `mat`.

In [ ]:
# Expected output: 325
# Your code here
print(mat.sum())

325


### Q27. Get the standard deviation of all values in `mat`.

In [ ]:
# Your code here
print(mat.std())

7.211102550927978


### Q28. Get the sum of each **column** in `mat`.
Expected output: `array([55, 60, 65, 70, 75])`

In [ ]:
# Your code here
print(mat.sum(axis=0))


[55 60 65 70 75]


### Q29. Get the sum of each **row** in `mat`.
Expected output: `array([ 15,  40,  65,  90, 115])`

In [ ]:
# Your code here
print(mat.sum(axis=1))

[ 15  40  65  90 115]


### Q30. Find the mean of all values in `mat`.

In [ ]:
# Your code here
print(mat.mean())


13.0


---
## Bonus Challenge

### B1. Create a 4x4 array of random integers between 1 and 50. Then:
1. Print the array
2. Print its transpose
3. Print the element-wise square root of the array (use `np.sqrt`)
4. Print the index of the largest value in the flattened array

In [ ]:
np.random.seed(0)  # Keep this for reproducibility
# Your code here
import numpy as np

arr=np.random.randint(1,50,(4,4))
print(arr)
print()
print(arr.T)
print()
print(np.sqrt(arr))
max_index_flat = arr.argmax()
print(f"\n4. موقع أكبر قيمة في المصفوفة المسطحة: {max_index_flat}")
print(f"   القيمة الأكبر هي: {arr.flatten()[max_index_flat]}")
print(f"   موقعها في المصفوفة الأصلية (صف, عمود): {np.unravel_index(max_index_flat, arr.shape)}")

[[45 48  1  4]
 [ 4 40 10 20]
 [22 37 24  7]
 [25 25 13  2]]

[[45  4 22 25]
 [48 40 37 25]
 [ 1 10 24 13]
 [ 4 20  7  2]]

[[6.70820393 6.92820323 1.         2.        ]
 [2.         6.32455532 3.16227766 4.47213595]
 [4.69041576 6.08276253 4.89897949 2.64575131]
 [5.         5.         3.60555128 1.41421356]]

4. موقع أكبر قيمة في المصفوفة المسطحة: 1
   القيمة الأكبر هي: 48
   موقعها في المصفوفة الأصلية (صف, عمود): (np.int64(0), np.int64(1))


### B2. Using only NumPy, create an 8x8 checkerboard pattern (0s and 1s).
Expected output:
```
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 ...]
```
*Hint: Try using `np.zeros` and index slicing with steps.*

In [ ]:
# Your code here
import numpy as np

checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1

print(" (8×8):")
print(checkerboard)


 (8×8):
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


---
# Great Job! 🎉
Once you're done, review your answers and make sure each cell produces the expected output.